agreements: {
    agreement_fetch_info_error: "暂时无法从服务器获取协议，请稍等一分钟后再试。",
    agreement_declined: "协议被拒绝"
},
accountPanel: {
    account_panel_presence_online: "在线",
    account_panel_presence_away: "离开",
    account_panel_presence_dnd: "勿扰",
    account_panel_presence_invisible: "隐身",
    account_panel_presence_playing: "游戏中",
    account_panel_referral_copy_label: "复制链接",
    account_panel_referral_copied_label: "已复制！"
},
appHeader: {
    app_header_menu: "菜单",
    app_header_volume: "音量",
    app_header_volume_mute: "静音",
    app_header_volume_unmute: "取消静音",
    app_header_account: "账户",
    app_header_account_name: "用户名",
    app_header_account_moniker: "@社区昵称",
    app_header_menu_get_help: "获取帮助",
    app_header_menu_spectrum: "光谱",
    app_header_menu_issue_council: "问题理事会",
    app_header_menu_discover: "探索启动器",
    app_header_menu_exit_the_app: "退出程序",
    app_header_menu_settings: "设置",
    app_header_actions_download: "下载",
    app_header_actions_menu_rsi_status: "RSI 状态",
    app_header_actions_menu_rsi_account: "RSI 账户",
    app_header_actions_menu_log_out: "登出",
    app_header_top_action_badge: "徽章",
    app_header_top_action_friends: "好友",
    app_header_account_block_title: "账户管理",
    app_header_account_block_subtitle: "管理您的档案，查看账单或访问您的机库",
    app_header_account_item_dashboard: "账户仪表盘",
    app_header_account_item_hangar: "我的机库",
    app_header_account_item_organizations: "组织",
    app_header_account_item_redeem: "兑换代码",
    app_header_account_dossier: "我的公民档案",
    app_header_loading: "正在进入宇宙…"
},
audioPlayer: {
    mini_player_unknown_track: "未知曲目",
    mini_player_unknown_artist: "未知艺术家",
    mini_player_previous_track: "上一首",
    mini_player_pause: "暂停",
    mini_player_play: "播放",
    mini_player_next_track: "下一首",
    mini_player_open_queue: "打开播放队列",
    mini_player_playback_controls: "播放控制",
    mini_player_progress_bar: "播放进度",
    audio_player_track_play: "播放 {{trackName}}",
    playlist_panel_aria_label: "播放列表",
    playlist_scrubber_controls_aria_label: "播放控制",
    playlist_shuffle: "随机播放",
    playlist_scrubber_aria_label: "曲目进度",
    playlist_loop_one: "单曲循环",
    playlist_next_in_queue: "即将播放",
    playlist_loading: "正在加载播放列表",
    playlist_discover_the_score: "探索配乐"
},
autoUpdate: {
    auto_update_dialog_close: "关闭",
    auto_update_dialog_title: "有可用的更新",
    auto_update_dialog_sub_title: "版本{{version}}",
    auto_update_dialog_no_update_content: "您当前正在运行的就是 RSI 启动器的最新版本。<0/>感谢您保持更新！",
    auto_update_dialog_no_update_action_primary_label: "继续",
    auto_update_dialog_update_available_content: "有新的 RSI 启动器版本可安装。程序将会关闭并重新启动。",
    auto_update_dialog_update_available_action_primary_label: "安装并重新启动",
    auto_update_dialog_update_available_action_secondary_label: "稍后安装",
    auto_update_dialog_update_install_failed_content: "无法更新至最新版本的启动器，请重新安装或联系<0>客户支持</0>",
    auto_update_dialog_update_install_failed_action_primary_label: "重新安装",
    auto_update_dialog_update_install_failed_action_secondary_label: "稍后安装",
    auto_update_dialog_update_quit_game_content: "游戏会话当前正在运行。如果你想要安装新版本启动器，将会关闭当前游戏会话，当前游戏进度可能会丢失",
    auto_update_dialog_update_quit_game_action_primary_label: "退出游戏并安装",
    auto_update_dialog_update_quit_game_action_secondary_label: "稍后再试",
    auto_update_toast_update_installed: "成功安装新版本启动器",
    auto_update_notification_failed_title: "启动器更新失败",
    auto_update_notification_failed_body: "RSI 启动器无法更新，将会继续运行当前版本。"
},
connection: {
    connection_title: "离线模式",
    connection_offline_information: "你目前处于离线状态，某些功能暂不可用。当你的网络恢复，你将自动重连。",
    connection_offline_trying_to_reconnect: "正在尝试重新连接",
    connection_toast_connection_available: "重连成功",
    connection_toast_action_continue_offline: "继续处于离线状态",
    connection_toast_warning_lost_connection_title: "你目前处于离线状态",
    connection_toast_warning_lost_connection_content: "你似乎处于离线状态。当你的网络恢复，你将自动重连。你可以在离线模式下继续使用启动器。",
    connection_toast_warning_lost_connection_remaining: "距离登出还有的离线时间"
},
contextMenu: {
    context_menu_copy: "复制",
    context_menu_paste: "粘贴",
    context_menu_cut: "剪切",
    context_menu_select_all: "全选"
},
dialog: {
    dialog_warning_logout_title: "登出",
    dialog_warning_logout_text: "你确定要登出账户吗？",
    dialog_warning_logout_game_running_text: "你确定要在游戏运行时登出账户吗？当前游戏进度可能会丢失。",
    dialog_warning_logout_confirm: "登出",
    dialog_warning_logout_error: "登出时发生错误。你的会话可能已经过期。请尝试重新登录。",
    dialog_warning_duplicate_library_title: "游戏库已存在",
    dialog_warning_duplicate_library_content: "你当前选择的位置已存在一个游戏库，请选择其他位置后重试",
    dialog_warning_delete_game_library_title: "删除游戏库",
    dialog_warning_delete_game_library_location: "你确定要删除以下游戏库？",
    dialog_warning_delete_game_library_games: "以下游戏当前使用此游戏库：",
    dialog_warning_delete_game_library_content: "将会使用默认游戏库。请确保将游戏文件夹移动到正确的位置。",
    dialog_warning_set_default_library_title: "更改默认游戏库",
    dialog_warning_set_default_library_content: "你确定要将以下游戏库设置为新安装游戏的默认位置？",
    dialog_action_set_default_library: "设置为默认",
    dialog_action_cancel: "取消",
    dialog_action_confirm: "确认",
    dialog_action_proceed: "继续",
    dialog_action_acknowledge: "我已知悉",
    dialog_action_ok: "OK",
    dialog_action_retry: "重试",
    dialog_action_close: "关闭",
    dialog_action_accept: "同意",
    dialog_action_decline: "拒绝",
    dialog_action_verify: "验证文件",
    dialog_action_install: "安装游戏",
    dialog_action_relaunch: "重新启动",
    dialog_action_discard: "放弃",
    dialog_action_delete: "删除",
    dialog_action_accept_risk_continue: "自行承担风险 & 继续",
    dialog_action_browse_library: "浏览游戏库",
    dialog_warning_back_launcher: "返回启动器",
    dialog_warning_exit_app_title: "退出程序",
    dialog_warning_exit_app_text: "你确定要退出该应用程序吗？",
    dialog_warning_exit_app_checkbox: "不再显示",
    dialog_warning_exit_app_confirm: "退出程序",
    dialog_warning_exit_app_game_running_text: "你无法在游戏运行时退出该应用程序。",
    dialog_warning_uninstall_title: "卸载 {{game}} - {{channel}}",
    dialog_warning_uninstall_text: "你确定要从你的电脑卸载该游戏吗？请注意，你的电脑上的所有用户都会卸载该游戏文件。",
    dialog_warning_uninstall_userFolder_checkbox: "保留用户文件夹（按键绑定和设置偏好）",
    dialog_warning_uninstall_userFolder_checkbox_description: "目录位置：{{path}}",
    dialog_warning_uninstall_confirm: "卸载游戏",
    dialog_settings_reset_title: "重置设置",
    dialog_settings_reset_content: "你确定要重置你的游戏设置吗？",
    dialog_settings_reset_button: "重置至默认",
    dialog_settings_game_not_installed_title: "游戏未安装",
    dialog_settings_game_not_installed_content: "当前你尝试验证文件的位置并未安装游戏。请先安装游戏后重试。",
    dialog_cancel_installation_title: "取消安装",
    dialog_cancel_installation_content: "你确定要取消安装 {{info}} 吗？",
    dialog_cancel_install_title: "取消安装",
    dialog_cancel_install_content: "你确定要取消安装 {{info}} 吗？",
    dialog_cancel_install_content_keep_files_downloaded: "保留已下载的文件",
    dialog_cancel_verify_title: "取消验证文件",
    dialog_cancel_verify_content: "你确定要取消验证 {{info}} 吗？",
    dialog_cancel_update_title: "取消更新",
    dialog_cancel_update_content: "你确定要取消更新 {{info}} 吗？",
    dialog_start_installation_title: "安装 {{game}} - {{channel}}",
    dialog_start_installation_content_location: "游戏将安装在以下位置",
    dialog_start_installation_content_location_settings: "你可以在游戏设置中更改游戏位置",
    dialog_start_installation_content_location_close_popover: "如果你需要先更改游戏安装位置，请关闭此对话框。",
     dialog_start_installation_content_space_available: "可用空间：",
    dialog_start_installation_content_space_required: "所需空间：",
    dialog_start_installation_content_calculating_size: "正在计算空间...",
    dialog_start_installation_content_warning_space_available_timeout: "可用空间计算耗时超出预期，继续操作可能存在风险。",
    dialog_start_installation_content_warning_space_available_error: "无法计算可用空间，继续操作可能存在风险。",
    dialog_start_installation_content_warning_space_required_timeout: "所需空间计算耗时超出预期，继续操作可能存在风险。",
    dialog_start_installation_content_warning_space_required_error: "无法计算所需空间，继续操作可能存在风险。",
    dialog_start_installation_content_warning_not_enought_space: "请释放磁盘空间或更改安装位置。",
    dialog_start_installation_content_info_space_required_already_allocated: "所需空间已在您的驱动器上完成预留。",
    dialog_start_installation_action_go_to_settings: "游戏设置",
    dialog_start_installation_install_title: "安装 {{game}} - {{channel}}",
    dialog_start_installation_update_title: "更新 {{game}} - {{channel}}",
    dialog_start_installation_action_install: "安装",
    dialog_start_installation_action_update: "更新",
    dialog_launch_check_update_available_title: "游戏版本更新",
    dialog_launch_check_update_available_content: "一个新的游戏版本 {{game}} - {{channel}} 可用。请更新后再进入游戏。",
    dialog_discover_title: "启动器更新了 UI ！",
    dialog_discover_content: "RSI 启动器的外观焕然一新！我准备了一个小旅程带你去看看有什么变化。",
    dialog_discover_start: "开启旅程",
    dialog_discover_skip: "跳过",
    dialog_debug_cache_clear_title: "清除启动器缓存",
    dialog_debug_cache_clear_content: "此操作将清除启动器缓存并退出登录，你确定要继续吗？",
    dialog_debug_cache_clear_button: "继续",
    dialog_warning_change_game_title_dialog: "更改游戏位置",
    dialog_warning_change_game_question_dialog: "{{game}} - {{channel}} 已安装至当前位置。你想要更改游戏库吗？",
    dialog_warning_change_installed_game_question_dialog: "你确定要更改此游戏库的位置？",
    dialog_warning_change_game_current_dialog: "当前：",
    dialog_warning_change_game_new_dialog: "新：",
    dialog_warning_change_game_warn_dialog: "如要继续，请确保将文件移动到新位置，并在新位置验证文件或重新安装游戏。",
    dialog_settings_delete_local_title: "管理本地配置",
    dialog_promotion_logout_title: "促销活动已应用",
    dialog_promotion_logout_message: "恭喜！您的账户已可以加入免费试飞活动。请重新登录以进入游戏。",
    dialog_promotion_error_title: "无法应用促销活动",
    dialog_promotion_error_message: "此促销活动无法应用于您的账户。请访问<0>促销活动页面</0>并使用以下代码激活：",
    dialog_system_requirements_title: "未达到配置要求",
    dialog_system_requirements_text_1: "你的 PC 未达到运行 {{game}} 的最低配置要求。",
    dialog_system_requirements_text_2: "如果继续运行，可能会出现游戏崩溃或性能不佳的情况。",
    dialog_system_requirements_text_3: "配置要求：",
    dialog_system_requirements_os_min_version: "Windows 10 或更高版本",
    dialog_system_requirements_cpu_arch: "x86 CPU 架构",
    dialog_system_requirements_cpu_avx: "支持 AVX 指令集",
    dialog_system_requirements_cpu_avx2: "支持 AVX2 指令集",
    dialog_system_requirements_cpu_fma3: "支持 FMA3 指令集",
    dialog_system_requirements_link: "需要帮助？<0>查看完整配置要求</0>"
},
discover: {
    step_done_label: "立即进入",
    step_menu_title: "启动器应用菜单",
    step_menu_description: "在此菜单中可快速访设置和其他有用的资源，例如：支持、光谱和问题理事会。",
    step_status_title: "状态",
    step_status_description: "在此可查看 RSI 各项服务的状态。如果有任何性能问题或服务中断，你可以在此处看到。",
    step_download_title: "下载管理",
    step_download_description: "查看下载/更新进度、暂停当前下载或快速访问下载设置。",
    "step_user-profile_title": "用户档案",
    "step_user-profile_description": "查看当前登录的账户。使用此菜单可快速访问你的 RSI 账户界面。如果你需要切换账号，可在此登出。",
    step_last_title: "启动器发展",
    step_last_description: "RSI 启动器会随着时间的推移不断发展。请随时在问题理事会向我们反馈问题。感谢你对我们开发的支持。"
},
download: {
    download_empty: "下载队列中没有下载任务。",
    download_phase: "阶段",
    download_phase_compute_size: "正在计算所需磁盘空间",
    download_phase_disk_space_check: "正在检查磁盘空间",
    download_phase_initial_download: "正在启动下载",
    download_phase_patcher: "正在启动更新",
    download_status: "状态",
    download_speed: "速度",
    download_left: "剩余",
    download_files_left: "剩余文件",
    download_settings: "下载设置",
    download_play: "开始",
    download_pause: "暂停",
    download_initializing: "正在初始化…",
    download_update_manifest: "正在下载更新文件清单",
    download_manifest: "正在下载文件清单",
    downloaded_update_manifest: "更新文件清单已下载",
    download_analysing_install: "正在验证安装文件",
    download_checking_files: "正在验证文件 - 需要几分钟",
    download_base_pack: "正在下载基础文件包",
    download_updating_game_files: "正在更新游戏文件",
    download_updating_game_content: "正在更新游戏内容",
    download_verifying_game_content: "正在验证游戏内容",
    download_completed: "完成",
    download_waiting: "正在排队",
    download_cancelling: "正在取消",
    download_resume: "继续",
    download_cancel: "取消",
    download_remove: "移除",
    download_error: "错误",
    download_downloads_on_going: "进行中任务",
    download_downloads_waiting: "下一任务",
    download_downloads_finished: "完成",
    download_toast_install_success: "安装已完成",
    download_toast_update_success: "更新已完成",
    download_toast_verify_success: "文件验证已完成",
    download_toast_cancel_install_success: "安装已取消",
    download_toast_cancel_verify_success: "文件验证已取消",
    download_toast_cancel_update_success: "更新已取消",
    download_toast_uninstall_success: "{{game}} - {{channel}} 已卸载",
    download_toast_uninstall_fail: "{{game}} - {{channel}} 无法卸载",
    download_toast_install_fail: "{{game}} - {{channel}} 无法安装",
    download_type_install: "安装",
    download_type_update: "更新",
    download_type_verify: "验证文件",
    download_toast_fix_permission_success: "权限已修复。请验证游戏文件以继续。",
    download_toast_fix_permission_fail: "修复 {{game}} - {{channel}} 权限失败。请重试。"
},
errors: {
    error_game_package_missing_title: "没有游戏资格包",
    error_game_package_missing_subtitle: "你需要购买一个游戏资格包以登录访问游戏。",
    error_game_package_missing_retry: "重试登录",
    error_game_package_missing_support: "客户支持",
    error_sign_in_offline_header_title: "你当前处于离线状态",
    error_sign_in_offline_header_subtitle: "无法连接至我们的服务器。请检查你的网络并重试。",
    error_sign_in_offline_content_title: "为什么我不能进入离线模式？",
    error_sign_in_offline_content_description: "你无法进入离线模式可能由以下原因之一造成：",
    error_sign_in_offline_content_description_first: "你还未选择 \u201c记住密码\u201d",
    error_sign_in_offline_content_description_second: "你的设备信任期限已过",
    error_sign_in_offline_content_description_third: "你在过去的30天内未登录过",
    error_sign_in_offline_exit: "退出",
    error_sign_in_offline_retry: "重试",
    error_internal_error: "内部错误",
    error_not_authenticated: "你未通过身份验证",
    error_invalid_claims: "无效声明",
    error_authentication_mfa: "身份验证需要mfa",
    error_sign_in_failed: "登入失败。你可能输入了错误的凭证。",
    "error_sign-in_failed": "登入失败。你可能输入了错误的凭证。",
    error_sign_in_not_authorized: "你没有权限访问此版本的 RSI 启动器。请从<0>该网页</0>下载公众版本。",
    error_captcha_invalid: "验证码无效",
    error_session_expired: "你的会话已过期。请再次确认你的密码。",
    error_wrong_credentials: "你可能输入了错误的凭证、账户不存在或账户未激活。",
    error_max_login_attempt: "已超过登入失败的最大次数。",
    error_wrong_mfa_code: "双重验证失败。你可能输入了一个错误或过期的验证码。",
    error_captcha_required: "需要验证验证码。",
    error_game_error_code: "游戏错误代码：{{ code }}",
    error_installer_error_code: "错误代码：{{ code }}",
    error_installer_support_permission_title: "权限不足",
    error_installer_support_permission_content: "你需要授予启动器权限才能在你的系统上执行安装操作。",
    error_installer_create_directory_title: "无法创建文件夹",
    error_installer_create_directory_content_1: "创建频道文件夹时出现错误。",
    error_installer_create_directory_content_2: "请手动创建频道文件夹，后重试。必须在以下路径上创建文件夹：",
    error_installer_more_info_content: "可在<0>知识库</0>中查阅更多相关信息。",
    error_installer_basepack_invalid_title: "基础文件包 - 文件无效",
    error_installer_basepack_invalid_content: "下载游戏时出现错误，请重试。",
    error_installer_disc_full_title: "磁盘空间不足",
    error_installer_disc_full_content: "你的磁盘没有足够的可用空间。请清理出空间或将目录移动至空间更大的磁盘。",
    error_installer_permissions_title: "文件系统权限错误",
    error_installer_permissions_content: "修补程序在写入时遇到权限问题。请检查目录权限并重试。",
    error_installer_permissions_action: "修复权限",
    error_installer_file_in_use_title: "文件被占用",
    error_installer_file_in_use_content: "游戏文件正在被占用。请关闭你打开的游戏文件后重试。",
    error_installer_pk4_corrupted_title: "游戏文件已损坏",
    error_installer_pk4_corrupted_content: "你的游戏文件已损坏且无法恢复。",
    error_installer_retrieve_manifest_title: "无法获取更新文件清单",
    error_installer_retrieve_manifest_content: "获取更新文件清单时发生网络错误。请检查你的网络连接-并重启启动器后重试。",
    error_installer_retry_download: "重试下载",
    error_installer_unknown_network_title: "未知网络错误",
    error_installer_unknown_network_content: "请检查你的网络并重试。",
    error_installer_base_p4k_corrupted_title: "基础文件包验证错误",
    error_installer_base_p4k_corrupted_content: "基础文件包验证失败。",
    error_installer_init_download_title: "下载初始化 - 基础文件包 - 错误",
    error_installer_patcher_title: "数据修补程序错误",
    error_installer_title: "安装程序错误",
    error_installer_patcher_generic_content: "安装时出现错误。可在<0>知识库</0>中查阅更多相关信息。",
    error_installer_generic_content: "安装时出现错误。",
    error_report_bug: "如果问题持续存在，请<0>汇报漏洞</0>。请同时附上你的<1>日志文件</1>。",
    error_generic_title: "启动器错误",
    error_generic_content: "出现错误。",
    error_launch_account_not_found_title: "复制你的账户到 PTU ",
    error_launch_account_not_found_content: "想要游玩公共测试宇宙（PTU），你需要复制账户到 PTU。请按照以下步骤<0>这里</0>并重试。",
    error_launch_unknown_title: "启动器 - 未知错误",
    error_launch_unknown_content: "启动游戏时出现错误。请验证游戏文件完整性。",
    error_launch_error_code: "游戏错误代码：{{ code }}",
    error_launch_no_game_files_title: "启动器 - 未找到游戏文件",
    error_launch_no_game_files_content: "启动游戏时出现错误。无法检索到游戏文件。请验证游戏文件完整性。",
    error_launch_EAC_title: "启动器 - EAC 错误",
    error_launch_EAC_content: "启动游戏时出现错误。EAC 检测到文件损坏。请验证游戏文件完整性。",
    error_launch_game_crash_title: "{{game}} 意外停止运行",
    error_launch_game_crash_content_1: "游戏运行时出现错误。",
    error_launch_game_crash_content_2: "请尝试重新启动游戏。如果问题持续存在，请验证你的安装文件。",
    error_launch_game_running_title: "游戏正在运行",
    error_launch_game_running_content: "游戏已经处于运行状态",
    error_launch_check_update_unavailable_title: "检查游戏版本失败",
    error_launch_check_update_unavailable_content: "检查游戏版本时出现错误。",
    error_launch_game_crash_info: "崩溃摘要：",
    error_launch_game_crash_retrieving_crash_info: "正在获取数据",
    error_launch_game_crash_could_not_retrieve_crash_info: "无法获取数据",
    error_api_denied_request_title: "API 拒绝请求",
    error_api_deprecated_request: "API 请求已弃用",
    error_api_denied_request_content: "出现错误。你的会话似乎已过期或被拒绝。你已登出，请重试。",
    error_api_validation_failed: "API 请求验证失败",
    error_api_too_many_requests_title: "请求过多",
    error_api_too_many_requests_content: "API 当前过载。请稍等几分钟后重试。",
    error_api_unavailable: "API 不可用。请稍等几分钟后重试。",
    error_api_internal_server_error: "我们的服务器遇到困难。请稍等几分钟后重试。",
    error_api_auth_expired_content: "你的会话已过期。请再次确认你的密码。",
    error_api_auth_expired_title: "会话已过期",
    error_api_platform_auth_title: "平台验证错误",
    error_api_platform_auth_content: "无法在 {{id}} 平台进行验证 {{error}}",
    error_network_issue_title: "网络问题",
    error_network_issue_content: "无法建立网络连接。请检查你的网络状态后尝试重新连接。",
    error_launch_game_crash_copy_title: "复制到剪贴板",
    error_launch_game_crash_copy_copied_label: "已复制！"
},
form: {
    sign_in_title: "登入 RSI 启动器",
    sign_in_email: "邮箱",
    sign_in_password: "密码",
    sign_in_remember_me: "记住密码",
    sign_in_forgot_password: "忘记密码？",
    sign_in_captcha: "验证码",
    sign_in_captcha_refresh: "刷新",
    sign_in_captcha_help: "输入上方图像中的文本。",
    sign_in_no_account: "没有账户？",
    sign_in_create_account: "创建一个！",
    sign_in_submit: "登入",
    sign_in_loading: "正在登入…",
    sign_in_prerelease: "这是RSI启动器的抢先发布版本",
    sign_in_internal_build: "这是RSI启动器的内部版本",
    sign_in_divider_or: "或",
    sign_in_mfa_title: "我们需要验证你的身份",
    sign_in_mfa_subtitle: "保护你的账户对于我们来说是非常重要的。我们向你账户绑定的邮箱发送了验证码。",
    sign_in_mfa_code_label: "验证码",
    sign_in_mfa_code_help: "输入发送到你的邮箱的代码或验证器中的代码。或者使用备用代码。",
    sign_in_mfa_device_label: "设备名称",
    sign_in_mfa_device_help: "为你当前设备输入一个名称。",
    sign_in_mfa_duration_label: "信任这个设备",
    sign_in_mfa_duration_help: "允许设备在选定的时间内跳过MFA验证。如果这是一个共享或公共设备，我们建议你选择“仅当前会话”。",
    sign_in_mfa_session: "仅当前会话",
    sign_in_mfa_day: "一天",
    sign_in_mfa_week: "一周",
    sign_in_mfa_month: "一个月",
    sign_in_mfa_year: "一年",
    sign_in_mfa_back_sign_in: "返回",
    sign_in_mfa_submit: "验证身份",
    sign_in_third_party_connecting: "正在连接服务器...",
    sign_in_third_party_connected_1: "在浏览器中完成连接。",
    sign_in_third_party_connected_2: "完成登录后，你将自动链接至此处。",
    sign_in_third_party_timeout_title: "连接超时",
    sign_in_third_party_error_title: "连接失败",
    sign_in_third_party_timeout: "服务器已终止你的连接请求。可能由于Web服务器不可用或负载过高导致。请取消当前操作并重新尝试。",
    sign_in_third_party_back: "返回",
    sign_in_third_party_cancel: "取消",
    sign_in_loading_entering_the_verse: "正在进入“宇宙”...",
    error_field_is_required: "必须输入该字段",
    error_email_field_is_required: "需要输入一个邮箱地址",
    error_password_field_is_required: "需要输入密码",
    error_code_required: "你必须输入你的代码",
    error_device_required: "你必须输入你的设备名称",
    error_device_min_length: "你的设备名称最少需要3个字符",
    text_field_show_password: "显示密码",
    text_field_hide_password: "隐藏密码"
},
gamePage: {
    game_page_sc_title: "进入<0/><1>{{name}} 宇宙</1>",
    game_page_sq42_title: "开启<0/><1>{{name}} 的史诗冒险之旅</1>",
    game_page_nav_title_one: "游戏",
    game_page_nav_title_other: "游戏",
    game_page_game_is_running: "游戏正在运行",
    game_page_installing: "正在安装…",
    game_page_installing_paused: "安装已暂停",
    game_page_updating: "正在更新…",
    game_page_updating_paused: "更新已暂停",
    game_page_verifying: "正在验证文件…",
    game_page_uninstalling: "正在卸载",
    game_page_verifying_paused: "验证已暂停",
    game_page_update_game: "更新游戏",
    game_page_launch_game: "启动游戏",
    game_page_install_game: "安装游戏",
    game_page_waiting_in_queue: "正在排队",
    game_page_channels: "游戏环境",
    game_page_settings: "游戏设置",
    game_page_settings_verify: "验证游戏文件",
    game_page_settings_show_in_explorer: "在资源管理器中打开",
    game_page_settings_disable_vr_mode: "禁用 VR 模式",
    game_page_settings_check_update: "检查更新",
    game_page_settings_uninstall: "卸载游戏",
    game_page_settings_check_update_toast_yes: "有新的 {{game}} - {{channel}} 更新可用。",
    game_page_settings_check_update_toast_no: "{{game}} - {{channel}} 已为最新版本",
    game_page_internal_build_banner_title: "仅供内部使用 - 请勿外传",
    game_page_internal_build_banner_description: "这是一个内部开发版本。请勿在公司外部分享截图、录像或访问。",
    game_page_internal_build_banner_suffix_staff_account: "员工账号",
    game_page_update_game_is_available: "了解 {{version}} 新内容，<0>请查看补丁说明</0>",
    game_page_vr_mode_enabled: "VR 模式已启用",
    game_page_game_is_not_available_offline: "你目前处于离线状态。运行 {{game}} 需要网络连接。",
    game_page_status_under_maintenance: "我们正在对其中一项服务进行维护。",
    game_page_status_issue: "我们正在解决一个问题。请自行承担风险。",
    game_page_status_more_information: "想要获取更多信息请查阅<0>状态页面</0>",
    game_page_cards_empty: "目前没有可用的内容",
    game_page_cards_loading: "正在加载内容。",
    game_page_cards_tab_community: "社区",
    "game_page_cards_tab_comm-links": "通讯链接",
    "game_page_cards_tab_new-citizens": "新手指南",
    "game_page_cards_tab_patch-notes": "补丁说明",
    game_page_card_button_label: "查看更多",
    game_page_discover_button_label: "探索",
    game_page_buy_game_package_button_label: "购买一个游戏资格包",
    game_page_access_free_fly_button_label: "进入免费试飞",
    game_page_access_free_fly_preparing_label: "正在准备进入",
    game_page_access_free_fly_remaining_message: "此免费试飞活动剩余时间：{{remainingTime}}"
},
guide: {
    guide_tab_label: "指导",
    guide_hub_find_title: "寻找一位向导",
    guide_hub_title: "寻找一位向导",
    guide_hub_guide_count_one: "{{count}}位向导可用",
    guide_hub_guide_count_other: "{{count}}位向导可用",
    guide_hub_refresh: "刷新",
    guide_hub_no_results: "没有符合这些主题的向导",
    guide_hub_no_results_hint: "请尝试放宽主题或语言筛选条件",
    guide_hub_offline: "向导系统需要网络连接",
    guide_hub_error: "加载向导时出了点问题",
    guide_hub_retry: "重试",
    guide_hub_loading: "正在加载向导…",
    guide_count_one: "{{count}}位向导可用",
    guide_count_other: "{{count}}位向导可用",
    guide_refresh: "刷新",
    guide_loading: "正在加载向导…",
    "guide_empty_no-results": "没有符合这些主题的向导，请尝试放宽筛选条件。",
    guide_empty_offline: "向导系统需要网络连接",
    guide_empty_description: "未提供描述",
    guide_filter_languages_trigger: "语言",
    guide_filter_languages_panel_title: "按语言筛选",
    guide_filter_languages_update_button: "应用",
    guide_filter_languages_close: "关闭",
    guide_card_request: "请求指导",
    guide_card_pending: "等待中…",
    guide_card_cooldown: "请等待 {{seconds}} 秒",
    guide_card_online: "在线",
    guide_card_playing: "游戏中",
    guide_card_away: "离开",
    guide_card_offline: "离线",
    guide_card_sessions_completed_one: "已完成 {{count}} 次指导",
    guide_card_sessions_completed_other: "已完成 {{count}} 次指导",
    guide_request_pending_title: "待处理的指导请求",
    guide_request_pending_count_one: "{{count}} 个待处理请求",
    guide_request_pending_count_other: "{{count}} 个待处理请求",
    guide_request_cancel: "取消",
    guide_request_accept: "接受",
    guide_request_decline: "拒绝",
    guide_request_remove: "移除",
    guide_request_remove_all: "移除所有已取消的请求",
    guide_request_timeout: "请求已超时",
    guide_request_cancelled: "请求已取消",
    guide_request_anonymous_guide_name: "你的向导",
    guide_request_accepted_toast: "{{name}} 接受了你的指导请求！",
    guide_request_declined_toast: "你的指导请求已被拒绝",
    guide_notification_anonymous_name: "一位星际公民",
    guide_request_received_toast: "{{name}} 正在请求指导",
    guide_request_received_notification_title: "新的指导请求",
    guide_request_received_notification_body: "{{name}} 正在请求你的帮助",
    guide_request_accepted_notification_title: "指导请求已接受",
    guide_request_accepted_notification_body: "{{name}} 接受了你的指导请求",
    guide_request_declined_notification_title: "指导请求已拒绝",
    guide_request_declined_notification_body: "{{name}} 拒绝了你的指导请求",
    guide_session_started_notification_title: "指导会话已开始",
    guide_session_started_notification_body: "你现在已与 {{name}} 建立连接",
    guide_pending_requests: "待处理请求",
    guide_incoming_requests: "收到的请求",
    guide_terminated_requests: "已结束的请求",
    guide_availability_toggle: "可用状态",
    guide_availability_available: "可用",
    guide_availability_unavailable: "不可用",
    guide_availability_select_proficiency: "请至少选择一项专长",
    guide_guide_title: "向导管理",
    guide_guide_available: "提供指导",
    guide_guide_unavailable: "暂不提供指导",
    guide_guide_incoming_title: "收到的请求",
    guide_guide_incoming_empty: "没有待处理请求",
    guide_guide_set_available: "将自己设为可用以接收请求",
    guide_chat_title: "指导会话",
    guide_chat_placeholder: "输入消息…",
    guide_chat_private_message_notice: "这是一条通过向导系统发送的私信",
    guide_chat_end_session: "结束会话",
    guide_chat_end_confirm_title: "结束本次指导会话？",
    guide_chat_end_confirm_body: "这将同时结束你与你的向导的会话。",
    guide_chat_end_confirm_cancel: "取消",
    guide_chat_end_confirm_end: "结束会话",
    guide_endorsement_title: "会话已结束",
    guide_endorsement_question: "你和这位向导一起游玩游戏了吗？",
    guide_endorsement_yes: "是",
    guide_endorsement_no: "否",
    guide_endorsement_topics_title: "他们在哪些方面帮助了你？",
    guide_endorsement_submit: "提交",
    guide_endorsement_skip: "跳过",
    guide_endorsement_thanks: "感谢你的反馈！",
    guide_cta_title: "刚来到这个宇宙？",
    guide_cta_body: "找一位经验丰富的玩家带你上手",
    guide_cta_button: "寻找一位向导",
    guide_session_indicator: "指导会话进行中",
    guide_session_started_banner: "已与 {{name}} 开始指导会话",
    guide_session_accepted_banner: "已接受你的请求。向你的向导打个招呼吧！",
    guide_close: "关闭",
    guide_collapsed_label: "指导会话对象：",
    guide_collapsed_continue: "继续",
    guide_toolbar_undock: "在独立窗口中打开指导中心",
    guide_toolbar_dock: "将指导系统放回启动器中",
    guide_toolbar_dock_tooltip: "放回",
    guide_toolbar_unread_count_one: "{{count}} 条未读消息",
    guide_toolbar_unread_count_other: "{{count}} 条未读消息",
    guide_widget_title_line_1: "指导",
    guide_widget_title_line_2: "中心",
    guide_widget_toggle_aria_label: "切换指导中心面板",
    guide_widget_undock_tooltip: "弹出",
    guide_widget_live_label: "进行中",
    guide_hub_become_button: "成为向导",
    guide_hub_player_subtitle: "向经验丰富的星际公民玩家寻求指导，帮助你掌握基础或提升技能。",
    guide_hub_guide_title: "向导之路",
    guide_hub_guide_subtitle: "你已注册成为向导，使用此中心选择你的游戏专长、管理请求并与其他公民交流。",
    guide_hub_onboarding_cta_prefix: "第一次来这？",
    guide_hub_onboarding_cta_link: "阅读向导入门文档。",
    guide_hub_onboarding_cta_url: "https://support.robertsspaceindustries.com/hc/en-us/articles/360038526034-Guide-System",
    guide_hub_become_title: "成为一名经验丰富的向导",
    guide_hub_become_subtitle: "星际公民 · 向导计划",
    guide_become_eyebrow: "星际公民 · 向导计划",
    guide_become_subtitle: "向导在各个阶段为公民提供帮助——从首次启动到掌握新技能。请查看以下要求进行申请。",
    guide_become_section_title: "要求",
    guide_become_requirements_label: "要求",
    guide_become_req_rsi: "RSI 账户",
    guide_become_req_rsi_done: "你已登录，可以继续。",
    guide_become_req_rsi_pending: "你需要登录 RSI 账户。",
    guide_become_req_game: "游戏资格包",
    guide_become_req_game_done: "很好，你已拥有游戏资格包。",
    guide_become_req_game_pending: "需要有一个游戏资格包才能成为向导。",
    guide_become_req_game_checking: "正在检查你的游戏资格包…",
    guide_become_cancel: "取消注册",
    guide_become_signup: "立即注册",
    guide_become_error: "注册时出现问题，请重试。",
    guide_delist: "注销",
    guide_delist_error: "注销时出了点问题，请重试。",
    guide_profile_no_description: "未设置描述",
    guide_profile_edit: "编辑",
    guide_profile_save: "保存",
    guide_profile_cancel: "取消",
    guide_profile_bio_placeholder: "向学员介绍你的经验…",
    guide_profile_save_error: "无法保存你的描述，请重试。",
    guide_languages_section: "你的语言",
    guide_languages_empty: "你的 RSI 档案中尚未设置语言。",
    guide_languages_edit: "编辑",
    guide_languages_panel_title: "你的语言：",
    guide_languages_update_button: "更新我的语言",
    guide_languages_close: "关闭",
    guide_proficiencies_section: "你今天想教授什么？",
    guide_proficiencies_save_error: "无法保存专长，请重试。",
    guide_proficiency_heading: "你今天想学习什么？",
    guide_filter_languages_cancel: "取消",
    guide_filter_language_remove: "移除 {{label}}",
    guide_profile_description_label: "你的描述",
    guide_chat_duration_label: "持续时间",
    guide_chat_send: "发送",
    guide_endorsement_description: "告诉我们你的会话体验如何。",
    guide_error_title: "出了点问题",
    guide_offline_title: "无网络连接"
},
settingsPage: {
    settings_main_title: "设置",
    settings_about_title: "关于",
    settings_application_title: "程序",
    settings_games_title: "游戏",
    settings_download_title: "下载",
    settings_dev_title: "开发 / QA",
    settings_storage_title: "存储空间",
    settings_nav_items_application: "程序",
    settings_nav_items_accessibility: "辅助功能",
    settings_nav_items_games: "游戏",
    settings_nav_items_about: "关于",
    settings_nav_items_download: "下载",
    settings_nav_items_storage: "存储空间",
    settings_nav_items_notifications: "通知",
    settings_nav_items_dev: "开发 \ud83d\ude80",
    settings_about_logo_alt: "CloudImperium©",
    settings_about_copyright: "© 2012 - {{year}} Cloud Imperium Rights LLC and Cloud Imperium Rights Ltd",
    settings_about_launcher_version: "启动器版本",
    settings_about_launcher_preversion: "（抢先版）",
    settings_about_launcher_internal_build: "（内部版）",
    settings_application_window_behavior_title: "窗口行为",
    settings_application_window_behavior_description: "此选项允许你在关闭窗口时退出该程序。",
    settings_application_window_behavior_close_to_quit: "启用 关闭窗口直接退出程序",
    settings_application_debug_tools_title: "启动器调试工具",
    settings_application_debug_tools_description: "如果你在使用启动器时遇到问题，清除缓存可能可以解决问题。你还需要找到你的日志文件，这可在你向<iclink>问题理事会</iclink>报告启动器问题时提供帮助。",
    settings_application_debug_tools_label: "调试工具",
    settings_application_debug_tools_button_clear_cache: "清除缓存",
    settings_application_debug_tools_button_get_logs: "获取日志文件",
    settings_application_debug_tools_button_cache_clear_success: "缓存已清除",
    settings_accessibility_title: "辅助功能",
    settings_accessibility_reduce_motion_title: "动画减弱",
    settings_accessibility_reduce_motion_description: "减弱启动器中的动画。例如：背景视频、图标动画和页面过渡动画。",
    settings_accessibility_reduce_motion_system_sync_title: "与操作系统同步",
    settings_accessibility_reduce_motion_system_sync_description: "跟随操作系统的动画减弱设置偏好",
    settings_accessibility_reduce_motion_background_video_toggle_title: "禁用背景视频",
    settings_accessibility_reduce_motion_background_video_toggle_description: "将背景视频替换成一张静态图片",
    settings_accessibility_reduce_motion_unessential_animation_toggle_title: "禁用非必要动画",
    settings_accessibility_reduce_motion_unessential_animation_toggle_description: "装饰性图标、标志、光标交互...",
    settings_accessibility_reduce_motion_transition_effects_toggle_title: "禁用页面过渡效果",
    settings_accessibility_reduce_motion_transition_effects_toggle_description: "各部分（页面、选项卡...）之间的过渡动画",
    settings_accessibility_reduce_motion_information_enabled: "操作系统的动画减弱已启用。",
    settings_accessibility_reduce_motion_information_disabled: "操作系统的动画减弱已停用。",
    settings_accessibility_reduce_motion_information_restart_link_label: "下次启动才会应用当前更改。<iclink>现在重新启动</iclink>。",
    settings_accessibility_audio_settings_title: "音频设置",
    settings_accessibility_audio_settings_description: "控制启动器不同声音的音量",
    settings_accessibility_audio_settings_main_volume: "主音量",
    settings_accessibility_audio_settings_music: "音乐",
    settings_accessibility_audio_settings_effects: "音效",
    settings_accessibility_audio_settings_dev_title: "启用音效",
    settings_accessibility_audio_settings_dev_description: "新音效功能开关（例如登录页面）",
    settings_notifications_title: "通知",
    settings_notifications_sound_title: "声音",
    settings_notifications_sound_enable_label: "启用收到通知的提示音",
    settings_notifications_sound_enable_description: "例如启动器更新和指导请求",
    settings_notifications_display_title: "显示",
    settings_notifications_display_description: "管理接收启动器提示消息的方式，如下载完成、启动器更新、向导请求等…",
    settings_notifications_display_overlay_label: "游戏内覆盖",
    settings_notifications_display_overlay_description: "在你游玩时显示在屏幕上",
    settings_notifications_display_overlay_test: "测试游戏内覆盖",
    settings_notifications_display_autohide_label: "自动隐藏于",
    settings_notifications_display_autohide_rsi_game: "在 RSI 游戏中",
    settings_notifications_display_autohide_fullscreen: "在任何其他全屏应用中",
    settings_notifications_display_desktop_label: "桌面",
    settings_notifications_display_desktop_description: "以标准系统桌面通知的形式显示",
    settings_notifications_display_desktop_test: "测试桌面通知",
    settings_notifications_privacy_title: "隐私",
    settings_notifications_privacy_hide_personal_label: "隐藏通知中的个人信息",
    settings_notifications_privacy_hide_personal_description: "头像和昵称不会在通知弹窗中显示",
    settings_notifications_test_title: "测试通知",
    settings_notifications_test_overlay_body: "游戏内覆盖预览",
    settings_notifications_test_desktop_body: "系统通知预览",
    settings_games_installation_title: "游戏位置",
    settings_games_installation_description: "这是你的游戏文件夹的路径。",
    settings_games_installation_information: "如果你的游戏已经安装在其他位置，在这里选择位置，然后点击验证文件。",
    settings_games_installation_path_title: "游戏位置完整路径",
    settings_games_installation_library_folder_success: "路径已更新",
    settings_games_installation_library_folder_change: "更改",
    settings_games_installation_library_folder_label: "RSI 目录位置",
    settings_games_game_files_title: "安装位置",
    settings_games_game_files_description: "安装/卸载此游戏频道或验证已安装的游戏文件完整性。",
    settings_games_game_files_verify_files: "验证游戏文件",
    settings_games_game_files_verifying_files: "正在验证游戏文件",
    settings_games_game_files_install_files: "安装游戏",
    settings_games_game_files_installing_files: "正在安装",
    settings_games_game_files_updating_files: "正在安装",
    settings_games_game_files_uninstall_files: "卸载游戏",
    settings_games_game_files_uninstalling_files: "正在卸载",
    settings_games_game_files_process_paused: "已暂停",
    settings_common_reset: "重置所有更改",
    settings_common_reset_confirmation: "此游戏频道的更改已被重置",
    settings_common_accordion_open_all: "全部展开",
    settings_common_accordion_close_all: "全部折叠",
    settings_common_back: "返回",
    settings_common_saved: "已保存",
    settings_download_main_title: "带宽使用",
    settings_download_main_content: "调整下行带宽以优化网速",
    settings_storage_main_title: "默认游戏库",
    settings_storage_main_description: "默认情况下，新游戏和环境将安装在此处。",
    settings_storage_default_library_folder_label: "游戏库位置",
    settings_storage_additional_libs_title: "其他游戏库",
    settings_storage_additional_libs_description: "在一个或多个驱动器中创建库",
    settings_storage_add_additional_libraries: "添加新游戏库",
    settings_download_concurrent_title: "同时下载数",
    settings_download_concurrent_desc: "调整同时下载的最大文件数。优化你的下载体验以匹配你的偏好和网络。",
    settings_download_speed_title: "限制下载速度",
    settings_download_speed_desc: "通过为每个并发下载连接设置每秒数据传输速率上限来调节下载速度。",
    settings_download_speed_unlimited: "无限制",
    settings_application_discover_behavior_title: "探索行为",
    settings_application_discover_behavior_description: "启动器探索仅在首次进入启动器时显示（或通过点击 RSI 菜单中的 探索 按钮）。此选项将允许您在负载时重新启用 探索 以进行测试。",
    settings_application_discover_behavior_isDiscoverDone: "isDiscoverDone",
    settings_download_dev_title: "下载设置",
    settings_download_dev_description: "更改游戏下载设置",
    settings_download_dev_force_datapatcher_toggle: "仅限数据修补程序（此设置不会持久保存）",
    settings_download_dev_force_datapatcher_description: '移除基础包（NMD）的下载，仅使用数据修补程序。前提条件：在开始下载前需手动创建"Data.p4k"文件。',
    settings_download_dev_enable_network_statistics_toggle: "启用网络统计（此设置不会持久保存）",
    settings_download_dev_enable_network_statistics_description: "在更新程序步骤中启用统计计算。需要在流程开始前启用。",
    settings_application_internal_overlay_title: "UI 设置",
    settings_application_internal_overlay_description: "更改应用程序的 UI 设置",
    settings_application_internal_overlay_input_toggle: "在游戏页面隐藏 '内部版本' 覆盖",
    settings_application_internal_overlay_input_description: "此更改在应用程序重启后将不会保留",
    settings_application_language_title: "语言",
    settings_application_language_description: "应用程序语言",
    settings_application_language_en: "英文",
    settings_application_language_fr: "法语",
    settings_games_launch_command_line: "其他命令行参数",
    settings_games_launch_disclaimer: "此操作将在你下次启动游戏时应用",
    settings_games_launch_hostname: "宇宙 Host",
    settings_games_launch_port: "宇宙端口",
    settings_games_launch_executable: "可执行",
    settings_games_launch_launch_options: "启动器选项",
    settings_games_launch_eac_title: "Easy Anti-Cheat",
    settings_games_launch_eac_description: "Easy Anti-Cheat 是许多流行游戏使用的反作弊服务。用于在多人PC游戏中阻止作弊和未授权的第三方软件的使用。",
    settings_games_launch_eac_informative: "你需要在上面设置正确的可执行文件以启用 绕过EAC",
    settings_games_launch_eac_disable: "启用 绕过Easy Anti-Cheat",
    settings_games_launch_default: "默认：",
    settings_games_info_move_directory: "如果你的游戏已安装在其他位置，请将你的游戏文件夹移动到以下游戏库位置",
    settings_games_info_complete_path: "完整路径：",
    settings_games_manage_game_libraries: "管理游戏库",
    settings_games_game_location_title: "游戏位置",
    settings_games_game_location_description: "选择要安装此游戏的游戏库",
    settings_action_set_default: "设置为默认",
    settings_action_delete_library: "删除游戏库",
    settings_toast_delete_lib_success: "游戏库已删除",
    settings_toast_default_lib_updated: "默认游戏库已更新",
    settings_toast_lib_added: "一个新的游戏库已创建",
    settings_games_local_title: "本地配置管理",
    settings_games_local_description: "选择需要删除的本地配置，这样可能可以帮助你解决在游戏中遇到的问题。",
    settings_games_local_button: "管理本地配置",
    settings_games_local_shaders_folder: "着色器文件夹",
    settings_games_local_screenshots_folder: "截图文件夹",
    settings_games_local_user_folder: "用户文件夹",
    settings_games_local_keybindings: "键位绑定（控制）",
    settings_games_local_settings: "设置偏好（配置）",
    settings_games_local_characters: "自定义角色",
    settings_games_local_delete_description: "请选择需要删除的文件。",
    settings_games_local_delete_success: "本地配置已删除。",
    settings_games_local_delete_error: "删除本地配置失败",
    settings_games_local_delete_error_message: "发生错误，请确保你尝试删除的文件未被占用后再试。",
    settings_games_vr_title: "VR 支持",
    settings_games_vr_enable_title: "启用 VR 模式",
    settings_games_vr_enable_description: "启动游戏时启用 VR 模式，以便进行头戴设备检测和兼容性设置。",
    settings_about_powered_by: "技术支持来自"
},
status: {
    status_title: "RSI 状态",
    status_empty: "不可用。",
    status_last_updated: "最后一次更新 {{time}}",
    status_last_updated_empty: "当前无可用数据。",
    status_more_information: "更多信息",
    status_major: "完全中断",
    status_partial: "部分中断",
    status_degraded: "服务降级",
    status_maintenance: "正在维护",
    status_operational: "正常运行"
},
tray: {
    tray_website: "访问网站",
    tray_report_bug: "汇报漏洞",
    tray_spectrum: "光谱",
    tray_community_hub: "社区中心",
    tray_support: "支持",
    tray_mute: "静音",
    tray_unmute: "取消静音",
    tray_logout: "登出",
    tray_quit: "退出"
}
