const SC_TOOLBOX_LOCALIZATION_ZHTW_MAP = {
            agreements: {
                agreement_fetch_info_error: "暫時無法從伺服器取得協議，請稍等一分鐘後再試一次。",
                agreement_declined: "協議被拒絕"
            },
            accountPanel: {
                account_panel_presence_online: "在線",
                account_panel_presence_away: "離開",
                account_panel_presence_dnd: "勿擾",
                account_panel_presence_invisible: "隱身",
                account_panel_presence_playing: "遊戲中",
                account_panel_referral_copy_label: "複製連結",
                account_panel_referral_copied_label: "已複製！"
            },
            appHeader: {
                app_header_menu: "選單",
                app_header_volume: "音量",
                app_header_volume_mute: "靜音",
                app_header_volume_unmute: "取消靜音",
                app_header_account: "帳戶",
                app_header_account_name: "使用者名稱",
                app_header_account_moniker: "@社群暱稱",
                app_header_menu_get_help: "取得幫助",
                app_header_menu_spectrum: "Spectrum",
                app_header_menu_issue_council: "問題與建議中心",
                app_header_menu_discover: "探索啟動器功能",
                app_header_menu_exit_the_app: "關閉程式",
                app_header_menu_settings: "設定",
                app_header_actions_download: "下載",
                app_header_actions_menu_rsi_status: "RSI 狀態",
                app_header_actions_menu_rsi_account: "RSI 帳戶",
                app_header_actions_menu_log_out: "登出",
                app_header_top_action_badge: "徽章",
                app_header_top_action_friends: "好友",
                app_header_account_block_title: "帳戶管理",
                app_header_account_block_subtitle: "管理您的檔案，查看帳單或存取您的機庫",
                app_header_account_item_dashboard: "帳戶儀表板",
                app_header_account_item_hangar: "我的機庫",
                app_header_account_item_organizations: "組織",
                app_header_account_item_redeem: "兌換代碼",
                app_header_account_dossier: "我的公民檔案",
                app_header_loading: "正在進入宇宙…"
            },
            audioPlayer: {
                mini_player_unknown_track: "未知曲目",
                mini_player_unknown_artist: "未知藝術家",
                mini_player_previous_track: "上一首",
                mini_player_pause: "暫停",
                mini_player_play: "播放",
                mini_player_next_track: "下一首",
                mini_player_open_queue: "開啟播放佇列",
                mini_player_playback_controls: "播放控制",
                mini_player_progress_bar: "播放進度",
                audio_player_track_play: "播放 {{trackName}}",
                playlist_panel_aria_label: "播放清單",
                playlist_scrubber_controls_aria_label: "播放控制",
                playlist_shuffle: "隨機播放",
                playlist_scrubber_aria_label: "曲目進度",
                playlist_loop_one: "單曲循環",
                playlist_next_in_queue: "即將播放",
                playlist_loading: "正在載入播放清單",
                playlist_discover_the_score: "探索配樂"
            },
            autoUpdate: {
                auto_update_dialog_close: "關閉",
                auto_update_dialog_title: "有更新等待安裝",
                auto_update_dialog_sub_title: "版本{{version}}",
                auto_update_dialog_no_update_content: "您目前正在執行的就是 RSI 啟動器的最新版本。<0/>感謝您保持更新！",
                auto_update_dialog_no_update_action_primary_label: "繼續",
                auto_update_dialog_update_available_content: "有新的 RSI 啟動器版本可安裝。程式將會關閉並重新啟動。",
                auto_update_dialog_update_available_action_primary_label: "安裝並重新啟動",
                auto_update_dialog_update_available_action_secondary_label: "稍後安裝",
                auto_update_dialog_update_install_failed_content: "無法更新至最新版本的啟動器，請重新安裝或聯繫<0>客戶支援</0>",
                auto_update_dialog_update_install_failed_action_primary_label: "重新安裝",
                auto_update_dialog_update_install_failed_action_secondary_label: "稍後安裝",
                auto_update_dialog_update_quit_game_content: "遊戲工作階段目前正在執行。如果您想要安裝新版本啟動器，將會關閉目前遊戲工作階段，正在進行的遊戲進度可能會遺失",
                auto_update_dialog_update_quit_game_action_primary_label: "退出遊戲並安裝",
                auto_update_dialog_update_quit_game_action_secondary_label: "稍後再試",
                auto_update_toast_update_installed: "成功安裝新版本啟動器",
                auto_update_notification_failed_title: "啟動器更新失敗",
                auto_update_notification_failed_body: "RSI 啟動器無法更新，將會繼續執行目前版本。"
            },
            connection: {
                connection_title: "離線模式",
                connection_offline_information: "您目前處於離線狀態，部分功能無法使用。當您的網路恢復時將會自動重新連線。",
                connection_offline_trying_to_reconnect: "正在嘗試重新連線",
                connection_toast_connection_available: "重新連線成功",
                connection_toast_action_continue_offline: "繼續保持離線狀態",
                connection_toast_warning_lost_connection_title: "您目前處於離線狀態",
                connection_toast_warning_lost_connection_content: "您似乎處於離線狀態。當您的網路恢復將會自動重新連線。您可以在離線模式下繼續使用啟動器。",
                connection_toast_warning_lost_connection_remaining: "距離登出的剩餘離線時間"
            },
            contextMenu: {
                context_menu_copy: "複製",
                context_menu_paste: "貼上",
                context_menu_cut: "剪下",
                context_menu_select_all: "全選"
            },
            dialog: {
                dialog_warning_logout_title: "登出",
                dialog_warning_logout_text: "您確定要登出帳戶嗎？",
                dialog_warning_logout_game_running_text: "您確定要在遊戲執行時登出帳戶嗎？正在進行的遊戲進度可能會遺失。",
                dialog_warning_logout_confirm: "登出",
                dialog_warning_logout_error: "登出時發生錯誤。您的工作階段可能已經過期。請嘗試重新登入。",
                dialog_warning_duplicate_library_title: "收藏庫已存在",
                dialog_warning_duplicate_library_content: "您目前選擇的位置已存在一個收藏庫，請選擇其他位置後重新嘗試",
                dialog_warning_delete_game_library_title: "刪除收藏庫",
                dialog_warning_delete_game_library_location: "您確定要刪除下列收藏庫嗎？",
                dialog_warning_delete_game_library_games: "下列遊戲目前使用此收藏庫：",
                dialog_warning_delete_game_library_content: "將會使用預設收藏庫。請確保將遊戲資料夾移動到正確的位置。",
                dialog_warning_set_default_library_title: "變更預設收藏庫",
                dialog_warning_set_default_library_content: "您確定要將下列收藏庫設定為新安裝遊戲的預設位置嗎？",
                dialog_action_set_default_library: "設為預設",
                dialog_action_cancel: "取消",
                dialog_action_confirm: "確認",
                dialog_action_proceed: "繼續",
                dialog_action_acknowledge: "我已了解",
                dialog_action_ok: "OK",
                dialog_action_retry: "重新嘗試",
                dialog_action_close: "關閉",
                dialog_action_accept: "同意",
                dialog_action_decline: "拒絕",
                dialog_action_verify: "驗證檔案",
                dialog_action_install: "安裝遊戲",
                dialog_action_relaunch: "重新啟動",
                dialog_action_discard: "放棄",
                dialog_action_delete: "刪除",
                dialog_action_accept_risk_continue: "接受風險並繼續",
                dialog_action_browse_library: "瀏覽收藏庫",
                dialog_action_cancel_download: "取消下載",
                dialog_warning_back_launcher: "返回啟動器",
                dialog_warning_exit_app_title: "關閉程式",
                dialog_warning_exit_app_text: "您確定要退出應用程式嗎？",
                dialog_warning_exit_app_checkbox: "不再顯示",
                dialog_warning_exit_app_game_running_text: "您確定要在遊戲執行時退出應用程式嗎？",
                dialog_warning_exit_app_confirm: "關閉程式",
                dialog_warning_uninstall_title: "解除安裝 {{game}} - {{channel}}",
                dialog_warning_uninstall_text: "您確定要從您的電腦解除安裝該遊戲嗎？請注意，您的電腦上的所有使用者都會解除安裝該遊戲檔案。",
                dialog_warning_uninstall_userFolder_checkbox: "保留使用者資料夾（按鍵綁定和偏好設定）",
                dialog_warning_uninstall_userFolder_checkbox_description: "目錄位置：{{path}}",
                dialog_warning_uninstall_confirm: "解除安裝遊戲",
                dialog_settings_reset_title: "重置設定",
                dialog_settings_reset_content: "您確定要重置您的遊戲設定嗎？",
                dialog_settings_reset_button: "恢復預設",
                dialog_settings_game_not_installed_title: "尚未安裝遊戲",
                dialog_settings_game_not_installed_content: "目前您嘗試驗證檔案的位置並未安裝遊戲。請先安裝遊戲後重新嘗試。",
                dialog_cancel_installation_title: "取消下載",
                dialog_cancel_installation_content: "您確定要取消下載{{info}}嗎？",
                dialog_cancel_installation_content_keep_files_downloaded: "保留已下載檔案",
                dialog_cancel_install_title: "取消安裝",
                dialog_cancel_install_content: "您確定要取消安裝 {{info}} 嗎？",
                dialog_cancel_install_content_keep_files_downloaded: "保留已下載的檔案",
                dialog_cancel_verify_title: "取消驗證檔案",
                dialog_cancel_verify_content: "您確定要取消驗證 {{info}} 嗎？",
                dialog_cancel_update_title: "取消更新",
                dialog_cancel_update_content: "您確定要取消更新 {{info}} 嗎？",
                dialog_start_installation_title: "安裝 {{game}} - {{channel}}",
                dialog_start_installation_content_location: "遊戲將安裝在下列位置",
                dialog_start_installation_content_location_settings: "您可以在遊戲設定中變更遊戲位置",
                dialog_start_installation_content_location_close_popover: "如果您需要先變更遊戲安裝位置，請關閉此對話框。",
                dialog_start_installation_content_space_available: "可用空間：",
                dialog_start_installation_content_space_required: "所需空間：",
                dialog_start_installation_content_calculating_size: "正在計算空間…",
                dialog_start_installation_content_warning_space_available_timeout: "可用空間計算時間超出預期，繼續操作可能有風險。",
                dialog_start_installation_content_warning_space_available_error: "無法計算可用空間，繼續操作可能有風險。",
                dialog_start_installation_content_warning_space_required_timeout: "所需空間計算時間超出預期，繼續操作可能有風險。",
                dialog_start_installation_content_warning_space_required_error: "無法計算所需空間，繼續操作可能有風險。",
                dialog_start_installation_content_warning_not_enought_space: "請釋放磁碟空間或變更安裝位置。",
                dialog_start_installation_content_info_space_required_already_allocated: "所需空間已在您的磁碟上完成配置。",
                dialog_start_installation_action_go_to_settings: "遊戲設定",
                dialog_start_installation_install_title: "安裝 {{game}} - {{channel}}",
                dialog_start_installation_update_title: "更新 {{game}} - {{channel}}",
                dialog_start_installation_action_install: "安裝",
                dialog_start_installation_action_update: "更新",
                dialog_launch_check_update_available_title: "遊戲版本更新",
                dialog_launch_check_update_available_content: "一個新的遊戲版本 {{game}} - {{channel}} 可安裝。請更新後再進入遊戲。",
                dialog_discover_title: "啟動器介面已更新！",
                dialog_discover_content: "RSI 啟動器的外觀現在已經煥然一新！我們準備了一小段旅程來引領您去看看有什麼樣的改變。",
                dialog_discover_start: "開始旅程",
                dialog_discover_skip: "跳過",
                dialog_debug_cache_clear_title: "清除啟動器快取",
                dialog_debug_cache_clear_content: "此操作將清除啟動器快取並退出登入，您確定要繼續嗎？",
                dialog_debug_cache_clear_button: "繼續",
                dialog_warning_change_game_title_dialog: "變更遊戲位置",
                dialog_warning_change_game_question_dialog: "{{game}} - {{channel}} 已安裝至目前位置。您想要變更收藏庫嗎？",
                dialog_warning_change_installed_game_question_dialog: "您確定要變更此收藏庫的位置嗎？",
                dialog_warning_change_game_current_dialog: "目前：",
                dialog_warning_change_game_new_dialog: "新：",
                dialog_warning_change_game_warn_dialog: "如果要繼續，請確保將檔案移動至新位置，並在新位置驗證檔案或重新安裝遊戲。",
                dialog_settings_delete_local_title: "刪除本機配置",
                dialog_promotion_logout_title: "促銷活動已應用",
                dialog_promotion_logout_message: "恭喜！您的帳戶已可以加入免費試飛活動。請重新登入以進入遊戲。",
                dialog_promotion_error_title: "無法應用促銷活動",
                dialog_promotion_error_message: "此促銷活動無法應用於您的帳戶。請訪問<0>促銷活動頁面</0>並使用以下代碼激活：",
                dialog_system_requirements_title: "未達到最低配置要求",
                dialog_system_requirements_text_1: "您的電腦未達到執行 {{game}} 的最低配置要求。",
                dialog_system_requirements_text_2: "如果繼續可能會遇到當機或性能不佳的情況。",
                dialog_system_requirements_text_3: "要求：",
                dialog_system_requirements_os_min_version: "Windows 10 或更高版本",
                dialog_system_requirements_cpu_arch: "x86 CPU 架構",
                dialog_system_requirements_cpu_avx: "AVX 功能支援",
                dialog_system_requirements_cpu_avx2: "AVX2 功能支援",
                dialog_system_requirements_cpu_fma3: "FMA3 功能支援",
                dialog_system_requirements_link: "需要幫助？ <0>查看完整系統要求</0>"
            },
            discover: {
                step_done_label: "立即進入",
                step_menu_title: "啟動器選單",
                step_menu_description: "在此選單中可快速前往設定與其他實用資源，例如：支援、Spectrum 和問題與建議中心。",
                step_status_title: "狀態",
                step_status_description: "在此處能夠檢視 RSI 各項服務的狀態。如果有任何性能問題或服務中斷，您可以在此處看到。",
                step_download_title: "下載管理",
                step_download_description: "查看下載/更新進度、暫停目前下載或快速變更下載設定。",
                "step_user-profile_title": "使用者檔案",
                "step_user-profile_description": "查看目前登入的帳戶。使用此選單能夠快速瀏覽您的 RSI 帳戶介面。如果您需要切換帳號，可以在此處進行登出。",
                step_last_title: "啟動器路線圖",
                step_last_description: "RSI 啟動器會隨著時間的推移不斷發展。請隨時在問題與建議中心向我們回饋問題。感謝您對我們開發的支援。"
            },
            download: {
                download_empty: "下載佇列中沒有下載任務。",
                download_phase: "階段",
                download_phase_compute_size: "正在計算所需空間",
                download_phase_disk_space_check: "正在檢查磁碟空間",
                download_phase_initial_download: "正在啟動下載",
                download_phase_patcher: "正在啟動更新",
                download_status: "狀態",
                download_speed: "速度",
                download_left: "剩餘",
                download_files_left: "剩餘檔案",
                download_title: "下載任務",
                download_settings: "下載設定",
                download_play: "開始",
                download_pause: "暫停",
                download_initializing: "正在初始化…",
                download_update_manifest: "正在下載更新檔案清單",
                download_manifest: "正在下載檔案清單",
                downloaded_update_manifest: "更新檔案清單已下載",
                download_analysing_install: "正在驗證安裝檔案",
                download_checking_files: "正在驗證檔案 - 需要幾分鐘",
                download_base_pack: "正在下載基礎檔案包",
                download_updating_game_files: "正在更新遊戲檔案",
                download_updating_game_content: "正在更新遊戲內容",
                download_verifying_game_content: "正在驗證遊戲內容",
                download_completed: "完成",
                download_waiting: "正在排隊",
                download_cancelling: "正在取消",
                download_resume: "繼續",
                download_cancel: "取消",
                download_remove: "移除",
                download_error: "錯誤",
                download_downloads_on_going: "進行中",
                download_downloads_waiting: "下一個",
                download_downloads_finished: "已完成",
                download_toast_install_success: "安裝已完成",
                download_toast_update_success: "更新已完成",
                download_toast_verify_success: "檔案驗證已完成",
                download_toast_install_cancel_success: "下載已取消",
                download_toast_cancel_install_success: "安裝已取消",
                download_toast_cancel_verify_success: "檔案驗證已取消",
                download_toast_cancel_update_success: "更新已取消",
                download_toast_uninstall_success: "{{game}} - {{channel}} 已移除",
                download_toast_uninstall_fail: "{{game}} - {{channel}} 無法移除",
                download_toast_install_fail: "{{game}} - {{channel}} 無法安裝",
                download_type_install: "安裝",
                download_type_update: "更新",
                download_type_verify: "驗證檔案",
                download_toast_fix_permission_success: "權限已修復。請驗證遊戲檔案以繼續。",
                download_toast_fix_permission_fail: "修復 {{game}} - {{channel}} 權限失敗。請重新嘗試。"
            },
            errors: {
                error_game_package_missing_title: "沒有遊戲資格包",
                error_game_package_missing_subtitle: "您需要購買一個遊戲資格包才能夠登入遊戲。",
                error_game_package_missing_retry: "重新登入",
                error_game_package_missing_support: "客戶支援",
                error_sign_in_offline_header_title: "您目前處於離線狀態",
                error_sign_in_offline_header_subtitle: "無法連線至我們的伺服器。請檢查您的網路並重新嘗試。",
                error_sign_in_offline_content_title: "為什麼我不能進入離線模式？",
                error_sign_in_offline_content_description: "您無法進入離線模式可能由下列其中一項原因導致：",
                error_sign_in_offline_content_description_first: "您還未選擇 \u201c記住密碼\u201d",
                error_sign_in_offline_content_description_second: "您的裝置信任期限已逾期",
                error_sign_in_offline_content_description_third: "您在過去的30天內未曾登入帳戶",
                error_sign_in_offline_exit: "退出",
                error_sign_in_offline_retry: "重新嘗試",
                error_internal_error: "內部錯誤",
                error_not_authenticated: "您未通過身份驗證",
                error_invalid_claims: "無效宣告",
                error_authentication_mfa: "身份驗證需要mfa",
                error_sign_in_failed: "登入失敗。您可能輸入了錯誤的憑證。",
                "error_sign-in_failed": "登入失敗。您可能輸入了錯誤的憑證。",
                error_sign_in_not_authorized: "您沒有登入權限。",
                error_captcha_invalid: "驗證碼無效",
                error_session_expired: "您的工作階段已過期。請再次確認您的密碼。",
                error_wrong_credentials: "您可能輸入了錯誤的憑證、帳戶不存在或帳戶未啟用(1032)",
                error_max_login_attempt: "已超過登入失敗的最大次數限制。(1034)",
                error_wrong_mfa_code: "雙重驗證失敗。您可能輸入了錯誤的或過期的驗證碼(1037)",
                error_captcha_required: "需要驗證驗證碼。",
                error_game_error_code: "遊戲錯誤代碼：{{ code }}",
                error_installer_error_code: "錯誤代碼：{{ code }}",
                error_installer_retry_download: "重新下載",
                error_installer_support_permission_title: "權限不足",
                error_installer_support_permission_content: "您需要授予啟動器權限才能在您的系統上執行安裝操作。",
                error_installer_create_directory_title: "無法建立資料夾",
                error_installer_create_directory_content_1: "建立頻道資料夾時出現錯誤。",
                error_installer_create_directory_content_2: "請手動建立頻道資料夾，後重新嘗試。必須在下列路徑上建立資料夾：",
                error_installer_more_info_content: "可在<0>知識庫</0>中查閱更多相關資訊。",
                error_installer_basepack_invalid_title: "基礎檔案包 - 檔案無效",
                error_installer_basepack_invalid_content: "下載遊戲時出現錯誤，請重新嘗試。",
                error_installer_disc_full_title: "磁碟空間不足",
                error_installer_disc_full_content: "您的磁碟沒有足夠的可用空間。請嘗試清理空間或將目錄移動至空間更大的磁碟。",
                error_installer_permissions_title: "檔案系統權限錯誤",
                error_installer_permissions_content: "修補程式在寫入時遇到權限問題。請檢查目錄權限並重新嘗試。",
                error_installer_permissions_action: "修復權限",
                error_installer_file_in_use_title: "檔案被佔用",
                error_installer_file_in_use_content: "遊戲檔案正在被佔用。請關閉您打開的遊戲檔案後重新嘗試。",
                error_installer_pk4_corrupted_title: "遊戲檔案已損壞",
                error_installer_pk4_corrupted_content: "您的遊戲檔案已損壞且無法恢復。",
                error_installer_retrieve_manifest_title: "無法取得更新檔案清單",
                error_installer_retrieve_manifest_content: "取得更新檔案清單時發生網路錯誤。請檢查您的網路連線，並重新啟動啟動器後再試。",
                error_installer_unknown_network_title: "未知網路錯誤",
                error_installer_unknown_network_content: "請檢查您的網路並重新嘗試。",
                error_installer_base_p4k_corrupted_title: "基礎檔案包驗證錯誤",
                error_installer_base_p4k_corrupted_content: "基礎檔案包驗證失敗，請重新嘗試。如果問題依然存在，請<0>回報漏洞</0>。別忘了附上您的<1>日誌檔案。</1>",
                error_installer_init_download_title: "下載初始化 - 基礎檔案包 - 錯誤",
                error_installer_patcher_title: "資料修補程式錯誤",
                error_installer_title: "安裝程式錯誤",
                error_installer_patcher_generic_content: "安裝時出現錯誤。可在<0>知識庫</0>中查閱更多相關資訊。",
                error_installer_generic_content: "安裝時出現錯誤。",
                error_report_bug: "如果問題依然存在，請<0>回報漏洞</0>。請同時附上您的<1>日誌檔案</1>。",
                error_generic_title: "啟動器錯誤",
                error_generic_content: "出現錯誤。",
                error_os_requirements_title: "未達到最低配置要求",
                error_os_requirements_text: "您的電腦未達到執行 {{ game }} 的<0>最低配置要求</0>",
                error_cpu_requirements_title: "檢測到不支援的硬體",
                error_cpu_requirements_text: "遊戲需要一個支援 AVX 指令集的 CPU 才能執行。",
                error_launch_account_not_found_title: "將您的帳戶複製到 PTU ",
                error_launch_account_not_found_content: "想要遊玩公共測試宇宙（PTU），您需要複製帳戶到 PTU。請按照下列步驟<0>這裡</0>並重新嘗試。",
                error_launch_unknown_title: "啟動器 - 未知錯誤",
                error_launch_unknown_content: "啟動遊戲時出現錯誤。請驗證遊戲檔案完整性。",
                error_launch_error_code: "遊戲錯誤代碼：{{ code }}",
                error_launch_no_game_files_title: "啟動器 - 未找到遊戲檔案",
                error_launch_no_game_files_content: "啟動遊戲時出現錯誤。無法檢索到遊戲檔案。請驗證遊戲檔案完整性。",
                error_launch_EAC_title: "啟動器 - EAC 錯誤",
                error_launch_EAC_content: "啟動遊戲時出現錯誤。EAC 檢測到檔案損壞。請驗證遊戲檔案完整性。",
                error_launch_game_crash_title: "{{game}} 意外停止執行",
                error_launch_game_crash_content_1: "遊戲執行時出現錯誤。",
                error_launch_game_crash_content_2: "請嘗試重新啟動遊戲。如果問題依然存在，請驗證您的安裝檔案。",
                error_launch_game_crash_info: "崩潰摘要：",
                error_launch_game_crash_retrieving_crash_info: "正在取得資料",
                error_launch_game_crash_could_not_retrieve_crash_info: "無法取得資料",
                error_launch_game_running_title: "遊戲正在執行",
                error_launch_game_running_content: "遊戲已經處於執行狀態",
                error_launch_check_update_unavailable_title: "檢查遊戲版本失敗",
                error_launch_check_update_unavailable_content: "檢查遊戲版本時出現錯誤。",
                error_api_denied_request_title: "API 拒絕請求",
                error_api_denied_request_content: "出現錯誤。您的工作階段似乎已過期或被拒絕。您已登出，請重新嘗試。",
                error_api_deprecated_request: "API 請求已棄用",
                error_api_validation_failed: "API 請求驗證失敗",
                error_api_too_many_requests_title: "請求過多",
                error_api_too_many_requests_content: "API 目前過載。請稍等幾分鐘後重新嘗試。",
                error_api_unavailable: "API 無法使用。請稍等幾分鐘後重新嘗試。",
                error_api_internal_server_error: "我們的伺服器遇到困難。請稍等幾分鐘後重新嘗試。",
                error_api_auth_expired_content: "您的工作階段已過期。請再次確認您的密碼。",
                error_api_auth_expired_title: "工作階段已過期",
                error_api_platform_auth_title: "平台驗證錯誤",
                error_api_platform_auth_content: "無法在 {{id}} 平台進行驗證 {{error}}",
                error_network_issue_title: "網路問題",
                error_network_issue_content: "無法建立網路連線。請檢查您的網路狀態後嘗試重新連線。",
                error_launch_game_crash_copy_title: "複製到剪貼簿",
                error_launch_game_crash_copy_copied_label: "已複製！"
            },
            form: {
                sign_in_title: "登入 RSI 啟動器",
                sign_in_email: "電子信箱",
                sign_in_password: "密碼",
                sign_in_remember_me: "記住密碼",
                sign_in_forgot_password: "忘記密碼？",
                sign_in_captcha: "驗證碼",
                sign_in_captcha_refresh: "重新整理",
                sign_in_captcha_help: "輸入上方圖像中的文字。",
                sign_in_no_account: "沒有帳戶？",
                sign_in_create_account: "建立一個！",
                sign_in_submit: "登入",
                sign_in_loading: "正在登入…",
                sign_in_prerelease: "這是RSI啟動器的搶先發布版本",
                sign_in_internal_build: "這是 RSI 啟動器的內部版本",
                sign_in_divider_or: "或",
                sign_in_mfa_title: "我們需要驗證您的身份",
                sign_in_mfa_subtitle: "保護您的帳戶對於我們來說是非常重要的。我們向您帳戶綁定的電子信箱發送了驗證碼。",
                sign_in_mfa_code_label: "驗證碼",
                sign_in_mfa_code_help: "輸入發送到您的電子信箱的驗證碼或驗證器中的驗證碼。或者使用備用驗證碼。",
                sign_in_mfa_device_label: "裝置名稱",
                sign_in_mfa_device_help: "為您目前裝置輸入一個名稱。",
                sign_in_mfa_duration_label: "信任這個裝置",
                sign_in_mfa_duration_help: "允許裝置在選定的時間內跳過MFA驗證。如果這是一個共享或公用裝置，我們建議您選擇“僅目前工作階段”。",
                sign_in_mfa_session: "僅目前工作階段",
                sign_in_mfa_day: "一天",
                sign_in_mfa_week: "一週",
                sign_in_mfa_month: "一個月",
                sign_in_mfa_year: "一年",
                sign_in_mfa_back_sign_in: "返回",
                sign_in_mfa_submit: "驗證身份",
                sign_in_third_party_connecting: "正在連線至伺服器…",
                sign_in_third_party_connected_1: "請在瀏覽器中完成連線。",
                sign_in_third_party_connected_2: "登入後，您將自動連線至此處。",
                sign_in_third_party_timeout_title: "連線逾時",
                sign_in_third_party_error_title: "連線失敗",
                sign_in_third_party_timeout: "伺服器已終止您的連線請求。網站伺服器可能無法使用或正忙碌中，請取消後重新嘗試。",
                sign_in_third_party_back: "返回",
                sign_in_third_party_cancel: "取消",
                sign_in_loading_entering_the_verse: "正在進入宇宙…",
                error_field_is_required: "必須輸入該欄位",
                error_email_field_is_required: "需要輸入一個電子信箱地址",
                error_password_field_is_required: "需要輸入密碼",
                error_code_required: "您必須輸入您的驗證碼",
                error_device_required: "您必須輸入您的裝置名稱",
                error_device_min_length: "您的裝置名稱最少需要3個字元",
                text_field_show_password: "顯示密碼",
                text_field_hide_password: "隱藏密碼"
            },
            gamePage: {
                game_page_title: "進入<0/><1>{{name}} 宇宙</1>",
                game_page_sc_title: "進入<0/><1>{{name}} 宇宙</1>",
                game_page_sq42_title: "開啟<0/><1>{{name}} 的史詩冒險之旅</1>",
                game_page_nav_title: "遊戲",
                game_page_nav_title_one: "遊戲",
                game_page_nav_title_other: "遊戲",
                game_page_game_is_running: "遊戲正在執行",
                game_page_installing: "正在安裝…",
                game_page_installing_paused: "安裝已暫停",
                game_page_updating: "正在更新…",
                game_page_updating_paused: "更新已暫停",
                game_page_verifying: "正在驗證檔案…",
                game_page_uninstalling: "正在移除",
                game_page_verifying_paused: "驗證已暫停",
                game_page_update_game: "更新遊戲",
                game_page_launch_game: "啟動遊戲",
                game_page_install_game: "安裝遊戲",
                game_page_waiting_in_queue: "正在排隊",
                game_page_channels: "遊戲環境",
                game_page_settings: "遊戲設定",
                game_page_settings_verify: "驗證遊戲檔案",
                game_page_settings_show_in_explorer: "在檔案總管中打開",
                game_page_settings_disable_vr_mode: "停用 VR 模式",
                game_page_settings_check_update: "檢查更新",
                game_page_settings_uninstall: "移除遊戲",
                game_page_settings_check_update_toast_yes: "有新的 {{game}} - {{channel}} 更新可用。",
                game_page_settings_check_update_toast_no: "{{game}} - {{channel}} 已為最新版本",
                game_page_internal_build_banner_title: "僅供內部使用 - 請勿分享",
                game_page_internal_build_banner_description: "這是內部開發版本。請勿在公司外部分享螢幕截圖、錄影或存取權限。",
                game_page_internal_build_banner_suffix_staff_account: "員工帳戶",
                game_page_update_game_is_available: "了解 {{version}} 新內容，<0>請查看補丁說明</0>",
                game_page_vr_mode_enabled: "VR 模式已啟用",
                game_page_game_is_not_available_offline: "您目前處於離線狀態。執行 {{game}} 需要網路連線。",
                game_page_status_under_maintenance: "我們正在對其中一項服務進行維護。",
                game_page_status_issue: "我們正在解決一個問題。請自行承擔風險。",
                game_page_status_more_information: "想要取得更多資訊請查閱<0>狀態頁面</0>",
                game_page_cards_empty: "目前沒有可用的內容",
                game_page_cards_loading: "正在載入內容。",
                game_page_cards_tab_community: "社群",
                "game_page_cards_tab_comm-links": "通訊連結",
                "game_page_cards_tab_new-citizens": "新手指南",
                game_page_cards_tab_patch_notes: "補丁說明",
                "game_page_cards_tab_patch-notes": "補丁說明",
                game_page_card_button_label: "查看更多",
                game_page_discover_button_label: "探索",
                game_page_buy_game_package_button_label: "購買一個遊戲資格包",
                game_page_access_free_fly_button_label: "進入免費試飛",
                game_page_access_free_fly_preparing_label: "正在準備進入",
                game_page_access_free_fly_remaining_message: "此免費試飛活動剩餘時間：{{remainingTime}}"
            },
            guide: {
                guide_tab_label: "指導",
                guide_hub_find_title: "尋找一位嚮導",
                guide_hub_title: "尋找一位嚮導",
                guide_hub_guide_count_one: "{{count}}位嚮導可用",
                guide_hub_guide_count_other: "{{count}}位嚮導可用",
                guide_hub_refresh: "重新整理",
                guide_hub_no_results: "沒有符合這些主題的嚮導",
                guide_hub_no_results_hint: "請嘗試放寬主題或語言篩選條件",
                guide_hub_offline: "嚮導系統需要網路連線",
                guide_hub_error: "載入嚮導時發生問題",
                guide_hub_retry: "重新嘗試",
                guide_hub_loading: "正在載入嚮導…",
                guide_count_one: "{{count}}位嚮導可用",
                guide_count_other: "{{count}}位嚮導可用",
                guide_refresh: "重新整理",
                guide_loading: "正在載入嚮導…",
                "guide_empty_no-results": "沒有符合這些主題的嚮導，請嘗試放寬篩選條件。",
                guide_empty_offline: "嚮導系統需要網路連線",
                guide_empty_description: "未提供描述",
                guide_filter_languages_trigger: "語言",
                guide_filter_languages_panel_title: "依語言篩選",
                guide_filter_languages_update_button: "套用",
                guide_filter_languages_close: "關閉",
                guide_card_request: "請求指導",
                guide_card_pending: "等待中…",
                guide_card_cooldown: "請等待 {{seconds}} 秒",
                guide_card_online: "在線",
                guide_card_playing: "遊戲中",
                guide_card_away: "離開",
                guide_card_offline: "離線",
                guide_card_sessions_completed_one: "已完成 {{count}} 次指導",
                guide_card_sessions_completed_other: "已完成 {{count}} 次指導",
                guide_request_pending_title: "待處理的指導請求",
                guide_request_pending_count_one: "{{count}} 個待處理請求",
                guide_request_pending_count_other: "{{count}} 個待處理請求",
                guide_request_cancel: "取消",
                guide_request_accept: "接受",
                guide_request_decline: "拒絕",
                guide_request_remove: "移除",
                guide_request_remove_all: "移除所有已取消的請求",
                guide_request_timeout: "請求已逾時",
                guide_request_cancelled: "請求已取消",
                guide_request_anonymous_guide_name: "您的嚮導",
                guide_request_accepted_toast: "{{name}} 接受了您的指導請求！",
                guide_request_declined_toast: "您的指導請求已被拒絕",
                guide_notification_anonymous_name: "一位星際公民",
                guide_request_received_toast: "{{name}} 正在請求指導",
                guide_request_received_notification_title: "新的指導請求",
                guide_request_received_notification_body: "{{name}} 正在請求您的幫助",
                guide_request_accepted_notification_title: "指導請求已接受",
                guide_request_accepted_notification_body: "{{name}} 接受了您的指導請求",
                guide_request_declined_notification_title: "指導請求已拒絕",
                guide_request_declined_notification_body: "{{name}} 拒絕了您的指導請求",
                guide_session_started_notification_title: "指導工作階段已開始",
                guide_session_started_notification_body: "您現在已與 {{name}} 建立連線",
                guide_pending_requests: "待處理請求",
                guide_incoming_requests: "收到的請求",
                guide_terminated_requests: "已結束的請求",
                guide_availability_toggle: "可用狀態",
                guide_availability_available: "提供指導",
                guide_availability_unavailable: "暫不提供指導",
                guide_availability_select_proficiency: "請至少選擇一項專長",
                guide_guide_title: "嚮導管理",
                guide_guide_available: "提供指導",
                guide_guide_unavailable: "暫不提供指導",
                guide_guide_incoming_title: "收到的請求",
                guide_guide_incoming_empty: "沒有待處理請求",
                guide_guide_set_available: "將自己設為可用以接收請求",
                guide_chat_title: "指導工作階段",
                guide_chat_placeholder: "輸入訊息…",
                guide_chat_private_message_notice: "這是一個由嚮導系統發起的私人訊息對話",
                guide_chat_end_session: "結束工作階段",
                guide_chat_end_confirm_title: "結束這次指導工作階段？",
                guide_chat_end_confirm_body: "這會同時結束您與嚮導的工作階段。",
                guide_chat_end_confirm_cancel: "取消",
                guide_chat_end_confirm_end: "結束工作階段",
                guide_endorsement_title: "工作階段已結束",
                guide_endorsement_question: "您和這位嚮導一起遊玩遊戲了嗎？",
                guide_endorsement_yes: "是",
                guide_endorsement_no: "否",
                guide_endorsement_topics_title: "他們在哪些方面幫助了您？",
                guide_endorsement_submit: "提交",
                guide_endorsement_skip: "略過",
                guide_endorsement_thanks: "感謝您的意見！",
                guide_cta_title: "剛來到這個宇宙？",
                guide_cta_body: "找一位經驗豐富的玩家帶您上手",
                guide_cta_button: "尋找一位嚮導",
                guide_session_indicator: "指導工作階段進行中",
                guide_session_started_banner: "已與 {{name}} 開始指導工作階段",
                guide_session_accepted_banner: "已接受您的請求。向您的嚮導打聲招呼吧！",
                guide_close: "關閉",
                guide_collapsed_label: "指導工作階段對象：",
                guide_collapsed_continue: "繼續",
                guide_toolbar_undock: "在獨立視窗中開啟指導中心",
                guide_toolbar_dock: "將指導系統放回啟動器中",
                guide_toolbar_dock_tooltip: "放回",
                guide_toolbar_unread_count_one: "{{count}} 則未讀訊息",
                guide_toolbar_unread_count_other: "{{count}} 則未讀訊息",
                guide_widget_title_line_1: "指導",
                guide_widget_title_line_2: "中心",
                guide_widget_toggle_aria_label: "切換指導中心面板",
                guide_widget_undock_tooltip: "彈出",
                guide_widget_live_label: "進行中",
                guide_hub_become_button: "成為嚮導",
                guide_hub_player_subtitle: "向經驗豐富的星際公民玩家尋求指導，幫助您掌握基礎或提升技能。",
                guide_hub_guide_title: "嚮導之路",
                guide_hub_guide_subtitle: "您已註冊成為嚮導，可使用此中心選擇遊戲專長、管理請求並與其他公民交流。",
                guide_hub_onboarding_cta_prefix: "第一次來這裡？",
                guide_hub_onboarding_cta_link: "閱讀嚮導入門文件。",
                guide_hub_onboarding_cta_url: "https://support.robertsspaceindustries.com/hc/en-us/articles/360038526034-Guide-System",
                guide_hub_become_title: "成為一名經驗豐富的嚮導",
                guide_hub_become_subtitle: "星際公民 · 嚮導計畫",
                guide_become_eyebrow: "星際公民 · 嚮導計畫",
                guide_become_subtitle: "嚮導在各個階段為公民提供幫助——從首次啟動到掌握新技能。請查看下列要求後申請。",
                guide_become_section_title: "要求",
                guide_become_requirements_label: "要求",
                guide_become_req_rsi: "RSI 帳戶",
                guide_become_req_rsi_done: "您已登入，可以繼續。",
                guide_become_req_rsi_pending: "您需要登入 RSI 帳戶。",
                guide_become_req_game: "遊戲資格包",
                guide_become_req_game_done: "很好，您已擁有遊戲資格包。",
                guide_become_req_game_pending: "需要有一個遊戲資格包才能成為嚮導。",
                guide_become_req_game_checking: "正在檢查您的遊戲資格包…",
                guide_become_cancel: "取消註冊",
                guide_become_signup: "立即註冊",
                guide_become_error: "註冊時發生問題，請重新嘗試。",
                guide_delist: "註銷",
                guide_delist_error: "註銷時發生問題，請重新嘗試。",
                guide_profile_no_description: "未設定描述",
                guide_profile_edit: "編輯",
                guide_profile_save: "儲存",
                guide_profile_cancel: "取消",
                guide_profile_bio_placeholder: "向學員介紹您的經驗…",
                guide_profile_save_error: "無法儲存您的描述，請重新嘗試。",
                guide_languages_section: "您的語言",
                guide_languages_empty: "您的 RSI 個人檔案中尚未設定語言。",
                guide_languages_edit: "編輯",
                guide_languages_panel_title: "您的語言：",
                guide_languages_update_button: "更新我的語言",
                guide_languages_close: "關閉",
                guide_proficiencies_section: "您今天想教授什麼？",
                guide_proficiencies_save_error: "無法儲存專長，請重新嘗試。",
                guide_proficiency_heading: "您今天想學習什麼？",
                guide_filter_languages_cancel: "取消",
                guide_filter_language_remove: "移除 {{label}}",
                guide_profile_description_label: "您的描述",
                guide_chat_duration_label: "時長",
                guide_chat_send: "傳送",
                guide_endorsement_description: "請告訴我們您的工作階段體驗如何。",
                guide_error_title: "發生了一些問題",
                guide_offline_title: "無網路連線"
            },
            settingsPage: {
                settings_main_title: "設定",
                settings_about_title: "關於啟動器",
                settings_application_title: "一般設定",
                settings_games_title: "遊戲檔案",
                settings_download_title: "下載設定",
                settings_dev_title: "Dev / QA",
                settings_storage_title: "儲存空間",
                settings_nav_items_application: "程式",
                settings_nav_items_accessibility: "輔助功能",
                settings_nav_items_games: "遊戲",
                settings_nav_items_about: "關於",
                settings_nav_items_download: "下載",
                settings_nav_items_storage: "儲存空間",
                settings_nav_items_notifications: "通知",
                settings_nav_items_dev: "DEV \ud83d\ude80",
                settings_about_logo_alt: "CloudImperium©",
                settings_about_copyright: "© 2012 - {{year}} Cloud Imperium Rights LLC and Cloud Imperium Rights Ltd",
                settings_about_launcher_version: "啟動器版本",
                settings_about_launcher_preversion: "（搶先版）",
                settings_about_launcher_internal_build: "（內部版）",
                settings_application_window_behavior_title: "視窗設定",
                settings_application_window_behavior_description: "開啟此功能將會停用啟動器最小化，並在您關閉視窗後直接關閉啟動器。",
                settings_application_window_behavior_close_to_quit: "啟用 關閉視窗直接關閉程式",
                settings_application_debug_tools_title: "啟動器除錯工具",
                settings_application_debug_tools_description: "如果您在使用啟動器時遇到問題，清除快取可能可以解決問題。您還需要找到您的日誌檔案，這可在您向<iclink>問題與建議中心</iclink>報告啟動器問題時提供幫助。",
                settings_application_debug_tools_label: "除錯工具",
                settings_application_debug_tools_button_clear_cache: "清除快取",
                settings_application_debug_tools_button_get_logs: "取得日誌檔案",
                settings_application_debug_tools_button_cache_clear_success: "快取已清除",
                settings_accessibility_title: "輔助功能",
                settings_accessibility_reduce_motion_title: "減少動畫效果",
                settings_accessibility_reduce_motion_description: "減少啟動器中的動畫效果。例如：背景影片、圖示動畫和頁面轉換動畫。",
                settings_accessibility_reduce_motion_system_sync_title: "與系統同步",
                settings_accessibility_reduce_motion_system_sync_description: "與系統的動畫減少設定同步",
                settings_accessibility_reduce_motion_background_video_toggle_title: "停用背景影片",
                settings_accessibility_reduce_motion_background_video_toggle_description: "使用靜態圖片取代背景影片",
                settings_accessibility_reduce_motion_unessential_animation_toggle_title: "停用非必要動畫",
                settings_accessibility_reduce_motion_unessential_animation_toggle_description: "裝飾性圖示、標誌、游標互動...",
                settings_accessibility_reduce_motion_transition_effects_toggle_title: "停用頁面轉換效果",
                settings_accessibility_reduce_motion_transition_effects_toggle_description: "各部分（頁面、頁籤...）之間的過渡動畫",
                settings_accessibility_reduce_motion_information_enabled: "系統的動畫減少已啟用。",
                settings_accessibility_reduce_motion_information_disabled: "系統的動畫減少已停用。",
                settings_accessibility_reduce_motion_information_restart_link_label: "下次啟動時才會套用目前變更。<iclink>立刻重新啟動</iclink>。",
                settings_accessibility_audio_settings_title: "音訊設定",
                settings_accessibility_audio_settings_description: "控制啟動器中不同聲音的音量",
                settings_accessibility_audio_settings_main_volume: "主音量",
                settings_accessibility_audio_settings_music: "音樂",
                settings_accessibility_audio_settings_effects: "音效",
                settings_accessibility_audio_settings_dev_title: "啟用音效",
                settings_accessibility_audio_settings_dev_description: "新音效功能開關（例如登入頁面）",
                settings_notifications_title: "通知",
                settings_notifications_sound_title: "聲音",
                settings_notifications_sound_enable_label: "啟用收到通知的提示音",
                settings_notifications_sound_enable_description: "例如啟動器更新和指導請求",
                settings_notifications_display_title: "顯示",
                settings_notifications_display_description: "管理接收啟動器提示訊息的方式，如下載完成、啟動器更新、嚮導請求等…",
                settings_notifications_display_overlay_label: "遊戲內覆蓋",
                settings_notifications_display_overlay_description: "在您遊玩時顯示在螢幕上",
                settings_notifications_display_overlay_test: "測試遊戲內覆蓋",
                settings_notifications_display_autohide_label: "自動隱藏於",
                settings_notifications_display_autohide_rsi_game: "在 RSI 遊戲中",
                settings_notifications_display_autohide_fullscreen: "在任何其他全螢幕應用程式中",
                settings_notifications_display_desktop_label: "桌面",
                settings_notifications_display_desktop_description: "以標準系統桌面通知的形式顯示",
                settings_notifications_display_desktop_test: "測試桌面通知",
                settings_notifications_privacy_title: "隱私權",
                settings_notifications_privacy_hide_personal_label: "隱藏通知中的個人資訊",
                settings_notifications_privacy_hide_personal_description: "頭像和暱稱不會在通知彈出視窗中顯示",
                settings_notifications_test_title: "測試通知",
                settings_notifications_test_overlay_body: "遊戲內覆蓋預覽",
                settings_notifications_test_desktop_body: "系統通知預覽",
                settings_games_installation_title: "遊戲位置",
                settings_games_installation_description: "這是您的遊戲資料夾的路徑。",
                settings_games_installation_information: "如果您的遊戲已經安裝在其他位置，在這裡選擇位置，然後點擊驗證檔案。",
                settings_games_installation_path_title: "遊戲位置完整路徑",
                settings_games_installation_library_folder_success: "路徑已更新",
                settings_games_installation_library_folder_change: "變更",
                settings_games_installation_library_folder_label: "RSI 目錄位置",
                settings_games_game_files_title: "安裝位置",
                settings_games_game_files_description: "安裝/解除安裝此遊戲頻道或驗證已安裝的遊戲檔案完整性。",
                settings_games_game_files_verify_files: "驗證遊戲檔案",
                settings_games_game_files_verifying_files: "正在驗證遊戲檔案",
                settings_games_game_files_install_files: "安裝遊戲",
                settings_games_game_files_installing_files: "正在安裝",
                settings_games_game_files_updating_files: "正在安裝",
                settings_games_game_files_uninstall_files: "解除安裝遊戲",
                settings_games_game_files_uninstalling_files: "正在解除安裝",
                settings_games_game_files_process_paused: "已暫停",
                settings_common_reset: "重置所有變更",
                settings_common_reset_confirmation: "此遊戲頻道的變更已被重置",
                settings_common_accordion_open_all: "全部展開",
                settings_common_accordion_close_all: "全部收起",
                settings_common_back: "返回",
                settings_common_saved: "已儲存",
                settings_download_main_title: "下載限制",
                settings_download_main_content: "調整下載速度來改善網路速率",
                settings_storage_main_title: "預設收藏庫",
                settings_storage_main_description: "預設情況下，新遊戲和環境將安裝在此處。",
                settings_storage_default_library_folder_label: "收藏庫位置",
                settings_storage_additional_libs_title: "其他收藏庫",
                settings_storage_additional_libs_description: "在一個或多個驅動器中建立庫",
                settings_storage_add_additional_libraries: "添加新收藏庫",
                settings_download_concurrent_title: "同時下載數量",
                settings_download_concurrent_desc: "調整同時下載的最大檔案數。提升您的下載體驗來匹配您的個人習慣和網路環境。",
                settings_download_speed_title: "限制下載速度",
                settings_download_speed_desc: "設定每秒資料傳輸速率上限以調節下載速率。",
                settings_download_speed_unlimited: "無限制",
                settings_application_discover_behavior_title: "探索功能",
                settings_application_discover_behavior_description: "啟動器探索僅在首次進入啟動器時顯示（或透過點擊 RSI 選單中的 探索 按鈕）。此選項將允許您在負載時重新啟用 探索 以進行測試。",
                settings_application_discover_behavior_isDiscoverDone: "isDiscoverDone",
                settings_download_dev_title: "下載設定",
                settings_download_dev_description: "變更遊戲下載設定",
                settings_download_dev_force_datapatcher_toggle: "僅使用資料修補程式（此設定不會保留）",
                settings_download_dev_force_datapatcher_description: '移除基礎包（NMD）的下載，僅使用資料修補程式。必要條件：開始下載前必須手動建立 "Data.p4k" 檔案。',
                settings_download_dev_enable_network_statistics_toggle: "啟用網路統計（此設定不會保留）",
                settings_download_dev_enable_network_statistics_description: "在更新程式階段啟用統計計算。必須在程序開始前啟用。",
                settings_application_internal_overlay_title: "UI 設定",
                settings_application_internal_overlay_description: "變更應用程式的 UI 設定",
                settings_application_internal_overlay_input_toggle: "在遊戲頁面隱藏「內部版本」覆蓋",
                settings_application_internal_overlay_input_description: "重新啟動應用程式後將不會保留此變更",
                settings_application_language_title: "語言",
                settings_application_language_description: "應用程式語言",
                settings_application_language_en: "英文",
                settings_application_language_fr: "法文",
                settings_games_launch_command_line: "其他命令列參數",
                settings_games_launch_disclaimer: "此操作將在您下次\u2019ll啟動遊戲時套用",
                settings_games_launch_hostname: "宇宙 Host",
                settings_games_launch_port: "宇宙埠",
                settings_games_launch_executable: "可執行",
                settings_games_launch_launch_options: "啟動器選項",
                settings_games_launch_eac_title: "Easy Anti-Cheat",
                settings_games_launch_eac_description: "Easy Anti-Cheat 是許多熱門遊戲所使用的反作弊服務。用於在多人PC遊戲中阻止作弊和未授權的第三方軟體的使用。",
                settings_games_launch_eac_informative: "您需要在上方設定正確的可執行檔案以啟用 繞過EAC",
                settings_games_launch_eac_disable: "啟用 繞過Easy Anti-Cheat",
                settings_games_launch_default: "預設：",
                settings_games_info_move_directory: "如果您的遊戲已安裝在其他位置，請將您的遊戲資料夾移動至下列收藏庫位置",
                settings_gmaes_info_complete_path: "完整路徑：",
                settings_games_info_complete_path: "完整路徑：",
                settings_games_manage_game_libraries: "管理收藏庫",
                settings_games_game_location_title: "遊戲位置",
                settings_games_game_location_description: "選擇要安裝此遊戲的收藏庫",
                settings_action_set_default: "設定為預設",
                settings_action_delete_library: "刪除收藏庫",
                settings_toast_delete_lib_success: "收藏庫已刪除",
                settings_toast_default_lib_updated: "預設收藏庫已更新",
                settings_toast_lib_added: "已建立一個新的收藏庫",
                settings_games_local_title: "本機配置",
                settings_games_local_description: "刪除本機配置將重置著色器和使用者資料夾，可能可以幫助您解決在遊戲中遇到的任何問題。",
                settings_games_local_button: "清除本機配置",
                settings_games_local_shaders_folder: "著色器資料夾",
                settings_games_local_screenshots_folder: "截圖資料夾",
                settings_games_local_user_folder: "使用者資料夾",
                settings_games_local_keybindings: "按鍵綁定（控制）",
                settings_games_local_settings: "偏好設定（配置）",
                settings_games_local_characters: "自訂角色",
                settings_games_local_delete_description: "請選擇需要刪除的檔案。",
                settings_games_local_delete_success: "本機配置已刪除。",
                settings_games_local_delete_error: "刪除本機配置失敗",
                settings_games_local_delete_error_message: "發生錯誤，請確保您嘗試刪除的檔案未被佔用後再試。",
                settings_games_vr_title: "VR 支援",
                settings_games_vr_enable_title: "啟用 VR 模式",
                settings_games_vr_enable_description: "啟動遊戲時啟用 VR 模式，以便進行頭戴式裝置偵測與相容性設定。",
                settings_about_powered_by: "技術支援來自"
            },
            status: {
                status_title: "RSI 伺服器狀態",
                status_empty: "暫無狀態可顯示。",
                status_last_updated: "最後更新於 {{time}}",
                status_last_updated_empty: "目前沒有資料。",
                status_more_information: "更多資訊",
                status_major: "完全斷線",
                status_partial: "部分斷線",
                status_degraded: "性能較差",
                status_maintenance: "正在維護",
                status_operational: "正常執行"
            },
            tray: {
                tray_website: "瀏覽網站",
                tray_report_bug: "回報漏洞",
                tray_spectrum: "Spectrum",
                tray_community_hub: "社群中心",
                tray_support: "支援",
                tray_mute: "靜音",
                tray_unmute: "取消靜音",
                tray_logout: "登出",
                tray_quit: "退出"
            }
        };
